version: '3'
services:
  myapp:
    build: router/deploy
    image: your-php-image:latest
    ports:
      - "8001:80"
  chroot:
    build: chroot/deploy
    ports:
      - "8002:22"
  avatar:
    build: avatar/deploy
    ports:
      - "8003:22"